# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='contact_email',
            field=models.EmailField(default='bob@bob.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='cost_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='gender',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='is_core_partner',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='is_cost_free',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='organizational_reach',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='service_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='setting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='student_need',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='tiers_of_ebp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='tiers_of_service',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='website',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
