# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('partners', '0002_auto_20170601_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='webinars',
            field=models.ManyToManyField(blank=True, to='core.Link'),
        ),
    ]
