# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
        ('partners', '0005_presentationslink_webinarlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='featured_network',
            field=models.ManyToManyField(blank=True, related_name='featured_partners', to='affiliates.Affiliate'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='gender',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='partner',
            name='grade',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='partner',
            name='organizational_reach',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='partner',
            name='service_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='partner',
            name='setting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='partner',
            name='student_need',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tiers_of_ebp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tiers_of_service',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='presentationslink',
            name='title',
            field=models.CharField(blank=True, help_text='Optional visible for link', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webinarlink',
            name='title',
            field=models.CharField(blank=True, help_text='Optional visible for link', max_length=100, null=True),
        ),
    ]
