# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20170601_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
