# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_partner_is_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationslink',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinarlink',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
