# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20170607_1315'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='partner',
            managers=[
                ('partners', django.db.models.manager.Manager()),
            ],
        ),
    ]
