# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20170607_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='tiers_of_ebp',
            new_name='tiers_of_evidence',
        ),
    ]
