version: 2
jobs:
  build:
    working_directory: ~/cis-network-directory
    docker:
      - image: circleci/python:3.6.1
        environment:
          DATABASE_URL: "postgres://root@localhost/circle_test"
          DEBUG: False
          DJANGO_AWS_ACCESS_KEY_ID: 1
          DJANGO_AWS_SECRET_ACCESS_KEY: 1
          DJANGO_AWS_STORAGE_BUCKET_NAME: 1
          MAILGUN_API_KEY: 1
          DJANGO_MAILGUN_API_KEY: 1
          MAILGUN_SENDER_DOMAIN: 1
          DJANGO_MAILGUN_SENDER_DOMAIN: 1
          DJANGO_SECRET_KEY: "kjjdkfjdkfj"
          DJANGO_SETTINGS_MODULE: "config.settings.production"
          DJANGO_SENTRY_DSN: "https://6df513965ac34cfc84c36aca3ce6a64a:572d668e8ab74cdf8e9f3b52833caabf@sentry.io/177351"
          DJANGO_ADMIN_URL: "^admin/"
          DJANGO_SECURE_SSL_REDIRECT: False
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/production.txt" }}-{{ checksum "requirements/test.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/test.txt
            pip install -r requirements/production.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/production.txt" }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python manage.py collectstatic
            pytest
            flake8 network_search
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "d2:eb:bf:5b:c9:fa:1a:cb:11:cf:c3:76:d3:2d:99:8b"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master
            fi
