# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 00:50
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='search_content',
            field=django.contrib.postgres.search.SearchVectorField(default=''),
            preserve_default=False,
        ),
    ]
