# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='race_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='region_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='study details',
            field=models.TextField(blank=True, help_text='Not for display', null=True),
        ),
    ]
