# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 15:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_search_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='grade',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=[], size=None),
            preserve_default=False,
        ),
    ]
