# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20170623_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='program',
            name='_tier_sorting',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
