# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
        ('programs', '0004_auto_20170601_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='network_use',
            field=models.ManyToManyField(blank=True, related_name='programs', to='affiliates.Affiliate'),
        ),
    ]
