# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_program_network_use'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='program',
            managers=[
                ('programs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
