# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20170607_1315'),
        ('programs', '0006_auto_20170607_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, help_text='Optional visible for link', max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatedResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, help_text='Optional visible for link', max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='program',
            name='assessment_available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='assessment_info',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='cost_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='gender',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='is_cost_free',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='national_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program', to='partners.Partner'),
        ),
        migrations.AddField(
            model_name='program',
            name='outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='race',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='region',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='setting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='student_characteristics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='student_needs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='study_weblink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tiers_of_evidence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='tiers_of_service',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='grade',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
        migrations.AddField(
            model_name='relatedresource',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_resources', to='programs.Program'),
        ),
        migrations.AddField(
            model_name='nationaldatabase',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_databases', to='programs.Program'),
        ),
    ]
