# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0003_auto_20170607_1314'),
        ('programs', '0007_auto_20170607_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='featured_network',
            field=models.ManyToManyField(blank=True, related_name='featured_programs', to='affiliates.Affiliate'),
        ),
    ]
