# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_program_featured_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='student_needs',
            new_name='student_need',
        ),
    ]
