# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 20:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20170607_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='core_service_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
