# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_program_core_service_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='core_service_categories',
            new_name='service_categories',
        ),
        migrations.AlterField(
            model_name='program',
            name='featured_network',
            field=models.ManyToManyField(blank=True, help_text="This is populated by first selecting affiliates for 'Network Use' and saving.", related_name='featured_programs', to='affiliates.Affiliate'),
        ),
    ]
