# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 21:20
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=400)),
                ('search_content', django.contrib.postgres.search.SearchVectorField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('affiliates', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EndOfYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField()),
                ('year_ends', models.IntegerField(help_text="This is the calendar year in which the EOY data ends. E.g. for the 2019-2020 year enter '2020'.")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
