# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 17:48
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='search_content',
            field=django.contrib.postgres.search.SearchVectorField(default=''),
            preserve_default=False,
        ),
    ]
