# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateEOYData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_eoy_data', to='affiliates.Affiliate')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEOYData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_eoy_data', to='affiliates.Affiliate')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEOYData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_eoy_data', to='affiliates.Affiliate')),
            ],
        ),
        migrations.AlterModelManagers(
            name='endofyear',
            managers=[
                ('years', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='endofyear',
            name='year_ends',
            field=models.IntegerField(help_text="This is the calendar year in which the EOY data ends. E.g. for the 2019-2020 year enter '2020'.", unique=True),
        ),
        migrations.AddField(
            model_name='studenteoydata',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_eoy_data', to='affiliates.EndOfYear'),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_eoy_data', to='affiliates.EndOfYear'),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_eoy_data', to='affiliates.EndOfYear'),
        ),
        migrations.AlterUniqueTogether(
            name='studenteoydata',
            unique_together=set([('affiliate', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='schooleoydata',
            unique_together=set([('affiliate', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='affiliateeoydata',
            unique_together=set([('affiliate', 'year')]),
        ),
    ]
