# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_auto_20170607_1248'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='affiliate',
            managers=[
                ('affiliates', django.db.models.manager.Manager()),
            ],
        ),
    ]
