# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0003_auto_20170613_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='Affiliate ID',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliate',
            name='address_city',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliate',
            name='address_postcode',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliate',
            name='address_state',
            field=models.CharField(default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliate',
            name='address_street',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliate',
            name='fax_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='official_name',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliate',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='state',
            field=models.CharField(default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliate',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
