# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_auto_20170613_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='Affiliate ID',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='cis_id',
            field=models.IntegerField(default=1, verbose_name='Affiliate ID'),
            preserve_default=False,
        ),
    ]
