# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 09:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0006_auto_20170616_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateeoydata',
            name='search_students_female',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='search_students_male',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='affiliate_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_data', to='affiliates.AffiliateEOYData'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affiliateeoydata',
            name='school_districts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, help_text='School district names should be separated by commas.', null=True, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='schooleoydata',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='schooleoydata',
            name='affiliate',
        ),
        migrations.RemoveField(
            model_name='schooleoydata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schooleoydata',
            name='year',
        ),
    ]
