# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0008_auto_20170619_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooleoydata',
            name='name',
            field=models.CharField(default=' ', max_length=400),
            preserve_default=False,
        ),
    ]
