# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0010_affiliateeoydata_search_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateeoydata',
            name='search_race',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='search_students_american_indian',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='search_students_asian',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='search_students_black',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='search_students_hispanic',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='search_students_other',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='search_students_two_or_more',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='search_students_white',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
