# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0011_auto_20170620_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('result', models.CharField(choices=[('p', 'Pending'), ('f', 'Failed'), ('s', 'Success')], default='p', editable=False, max_length=10)),
                ('data_file', models.FileField(null=True, upload_to='')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_uploads', to='affiliates.EndOfYear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='affiliateeoydata',
            name='search_students_american_indian',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='affiliateeoydata',
            name='search_students_asian',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='affiliateeoydata',
            name='search_students_black',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='affiliateeoydata',
            name='search_students_female',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='affiliateeoydata',
            name='search_students_hispanic',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='affiliateeoydata',
            name='search_students_male',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='affiliateeoydata',
            name='search_students_other',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='affiliateeoydata',
            name='search_students_two_or_more',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='affiliateeoydata',
            name='search_students_white',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
