# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0013_auto_20170621_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelupload',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
