# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0015_auto_20170622_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateeoydata',
            name='districts',
            field=models.TextField(blank=True, help_text='School district names should be separated by commas.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('f', 'Failed'), ('c', 'Completed')], default='p', editable=False, max_length=10),
        ),
    ]
