# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0016_auto_20170622_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooleoydata',
            name='service_categories',
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='budget_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='executive_director_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='executive_director_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='program_lead_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='program_lead_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='staff_fulltime_affiliate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='staff_fulltime_americorps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='staff_fulltime_non_affiliate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='staff_parttime_affiliate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='staff_parttime_americorps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='staff_parttime_non_affiliate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='service_academic_assistance',
            field=models.CharField(choices=[('s1', 'Services Provided by both CIS and Another Organization'), ('s2', 'No Services Delivered'), ('s3', 'Provided by CIS Staff'), ('s4', 'Brokered Services Delivered by Another Organization')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='service_basic_needs',
            field=models.CharField(choices=[('s1', 'Services Provided by both CIS and Another Organization'), ('s2', 'No Services Delivered'), ('s3', 'Provided by CIS Staff'), ('s4', 'Brokered Services Delivered by Another Organization')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='service_behavior_intervention',
            field=models.CharField(choices=[('s1', 'Services Provided by both CIS and Another Organization'), ('s2', 'No Services Delivered'), ('s3', 'Provided by CIS Staff'), ('s4', 'Brokered Services Delivered by Another Organization')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='service_college_career_prep',
            field=models.CharField(choices=[('s1', 'Services Provided by both CIS and Another Organization'), ('s2', 'No Services Delivered'), ('s3', 'Provided by CIS Staff'), ('s4', 'Brokered Services Delivered by Another Organization')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='service_comm_service',
            field=models.CharField(choices=[('s1', 'Services Provided by both CIS and Another Organization'), ('s2', 'No Services Delivered'), ('s3', 'Provided by CIS Staff'), ('s4', 'Brokered Services Delivered by Another Organization')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='service_enrichment',
            field=models.CharField(choices=[('s1', 'Services Provided by both CIS and Another Organization'), ('s2', 'No Services Delivered'), ('s3', 'Provided by CIS Staff'), ('s4', 'Brokered Services Delivered by Another Organization')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='service_family_engagement',
            field=models.CharField(choices=[('s1', 'Services Provided by both CIS and Another Organization'), ('s2', 'No Services Delivered'), ('s3', 'Provided by CIS Staff'), ('s4', 'Brokered Services Delivered by Another Organization')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='service_life_skills',
            field=models.CharField(choices=[('s1', 'Services Provided by both CIS and Another Organization'), ('s2', 'No Services Delivered'), ('s3', 'Provided by CIS Staff'), ('s4', 'Brokered Services Delivered by Another Organization')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='service_physical_fitness_health',
            field=models.CharField(choices=[('s1', 'Services Provided by both CIS and Another Organization'), ('s2', 'No Services Delivered'), ('s3', 'Provided by CIS Staff'), ('s4', 'Brokered Services Delivered by Another Organization')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='service_prof_mental_health',
            field=models.CharField(choices=[('s1', 'Services Provided by both CIS and Another Organization'), ('s2', 'No Services Delivered'), ('s3', 'Provided by CIS Staff'), ('s4', 'Brokered Services Delivered by Another Organization')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='site_type',
            field=models.CharField(blank=True, choices=[('ec', 'Early Childhood Education'), ('el', 'Elementary'), ('ms', 'Middle School'), ('hs', 'High School'), ('ps', 'Post-Secondary'), ('cm', 'Combined (any other K-12 combination)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='student_enrollment',
            field=models.IntegerField(default=0),
        ),
    ]
