# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 12:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0018_auto_20170623_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateeoydata',
            name='search_served',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='students_served_adjudicated_youth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='students_served_child_of_military',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='students_served_ell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='students_served_foster',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='students_served_gang',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='students_served_homeless',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='students_served_incarcerated_parent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='students_served_lgbt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='students_served_pregnant_parenting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='students_served_special_education',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='students_served_substance_abuse',
            field=models.IntegerField(default=0),
        ),
    ]
