# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0019_auto_20170624_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooleoydata',
            name='partners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
    ]
