# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0020_schooleoydata_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateeoydata',
            name='total_enrollment',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
