# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0021_affiliateeoydata_total_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateeoydata',
            name='funding_private_board',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='funding_private_cis_national',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='funding_private_cis_state_office',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='funding_private_corporate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='funding_private_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='funding_private_foundation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='funding_private_individual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='funding_private_npo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='funding_private_other',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='funding_public_city',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='funding_public_federal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='funding_public_school_district',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliateeoydata',
            name='funding_public_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='affiliate_location',
            field=models.CharField(choices=[('Ur', 'Urban'), ('S', 'Suburban'), ('R', 'Rural')], max_length=3),
        ),
    ]
