# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0022_auto_20170630_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_9',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_k',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooleoydata',
            name='students_grade_prek',
            field=models.IntegerField(default=0),
        ),
    ]
