# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0023_auto_20170712_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliate',
            options={'ordering': ['name'], 'verbose_name': 'Affiliate', 'verbose_name_plural': 'Affiliates'},
        ),
        migrations.AddField(
            model_name='affiliate',
            name='full_state_name',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
